# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name article')),
                ('quantity', models.CharField(max_length=15, verbose_name='quantity from articles')),
                ('description', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name from showcase')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name from store')),
                ('showcases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Showcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
