# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.RenameModel(
            old_name='Showcase',
            new_name='Showcases',
        ),
    ]
