# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170804_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='showcases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Showcases'),
        ),
    ]
